modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/Deftu/${mod_name}/issues"
license="LGPL-3.0-or-later"

[[mods]]
    modId="${mod_id}"
    version="${mod_version}"
    displayName="${mod_name}"
    authors="Deftu"
    description="${mod_description}"

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="[${minor_mc_version}]"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="textile"
    mandatory=true
    versionRange="[0.11.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="omnicore"
    mandatory=true
    versionRange="[0.24.3,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="textualizer"
    mandatory=true
    versionRange="[0.3.1,)"
    ordering="NONE"
    side="BOTH"